# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-06 07:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shortener', '0003_remove_kirrurl_timestamp1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='kirrurl',
            old_name='shotcode',
            new_name='shortcode',
        ),
    ]
